### ISSUE TITLE
Old Newsletter

### ISSUE THREAD

**Issue by joehand** [datproject/newsletter#1]
We sent out the first newsletter last month: https://mailchi.mp/881088ed65b0/dat-news-announcements-three-protocols-and-a-future-of-the-decentralized-internet-comm-comm-and-more

**Comment by RangerMauve** [comment]
Interesting! I missed out on it apparently. What did you do to put it together?

**Comment by joehand** [comment]
It was mostly unplanned - we had three blog posts the week before so I wanted to share them!

**Comment by RangerMauve** [comment]
Yeah, hopefully we can build up momentum from there. 😁

Did you just use the mailchimp interface to send it out?

**Comment by joehand** [comment]
| Did you just use the mailchimp interface to send it out?

Yes.
