### ISSUE TITLE
July Newsletter Planning

### ISSUE THREAD

**Issue by RangerMauve** [datproject/newsletter#11]
GPM https://github.com/geut/building-up-on-dat/tree/master/packages/gpm

Also get Diego's slides

**Comment by RangerMauve** [comment]
Diego's slides: https://building-up-on-dat.hashbase.io/#0

Alpha release of Cliqz concept browser, a Firefox based web browser for Android that integrates the dat-webext Firefox extension for Dat support. https://github.com/cliqz/cliqz-concept-browser/releases

**Comment by RangerMauve** [comment]
Initial release of the dat SDK: https://github.com/datproject/sdk

**Comment by RangerMauve** [comment]
hyperdrive-daemon got released. https://github.com/andrewosh/hyperdrive-daemon

**Comment by cblgh** [comment]
in cabal-related news i thought this was hilarious

https://twitter.com/_donblair/status/1151976620032450560

**Comment by decentral1se** [comment]
* DatPy
  * Cut a first alpha release of [merkle-tree-stream]()
  * Bashed out a [quick splash page](https://datpy.decentral1.se/) for discoverability/progress

Happy Hacking!

**Comment by RangerMauve** [comment]
K, gonna start drafting up the July newsletter today. :)

**Comment by RangerMauve** [comment]
https://www.kickscondor.com/wikipedia-on-dat-is-looking-sweet/

**Comment by cblgh** [comment]
technically august but: ack's landed for hypercore https://github.com/mafintosh/hypercore/pull/215

**Comment by RangerMauve** [comment]
https://cccfr.de/calendar/2019-07-26-DAT-peer2peer.html https://github.com/consento-org/cards

**Comment by RangerMauve** [comment]
Angelica from the SSB community is putting together a Dweb zine. dat://1db22c4a5a9a807c3990ca9c6d5735ba933076633dc9f27cd3d72e0eb2d6ce79/
