### ISSUE TITLE
August Newsletter Planning

### ISSUE THREAD

**Issue by RangerMauve** [datproject/newsletter#14]
SoapDog from SSB got Dat archives loading in Patchfox, a Firefox based SSB client. %efD09B2e/0R82ZgfKauE3neTpIstYlVXFkg3D5PgBMs=.sha256

**Comment by garrying** [comment]
Our Networks registration is open! https://ournetworks.ca

**Comment by RangerMauve** [comment]
BoomBox by @mixmix %ZjaDHJ8bnkW9MIDAcEmhHNF+Ofc3kJbPTLv2o7S6qng=.sha256

**Comment by RangerMauve** [comment]
@edsilv has been doing some cool stuff with Dat

- Slack bot for pinning archives: https://gitlab.com/mnemoscene/fusebot
- Electron based app for generating Universal Viewer files in Dat archives: https://github.com/UniversalViewer/uv.pub

**Comment by RangerMauve** [comment]
Putting this together for an issue now. 😁

**Comment by RangerMauve** [comment]
Zach! from SSB made this cool dat-zine: dat://a-hunger-artist.hashbase.io/

**Comment by RangerMauve** [comment]
Whoops, forgot to close this.
