### ISSUE TITLE
September Newsletter Planning

### ISSUE THREAD

**Issue by RangerMauve** [datproject/newsletter#16]
Feel free to post links to anything interesting you saw in September

**Comment by RangerMauve** [comment]
Andrew from SSB made a slide deck app %JMkASE4Crf6m204yyDmeD2YxtFwfDnVeRM9zA7UFsYE=.sha256

dat://7bbc546b3318114cba409c383a1d8dfe4b48081f5cdde7a05e0ab961a3904dcd/

https://github.com/andrew6767/dat-lwc-slides

**Comment by sammacbeth** [comment]
I'm writing some unofficial typescript type definitions for hyper* modules. These may be useful for people writing wanting to use the Dat ecosystem with typescript: https://github.com/sammacbeth/types

**Comment by cblgh** [comment]
the cabal club just released [`cabal-client`](https://github.com/cabal-club/cabal-client) which is an api for making distributed chat clients. it takes care of all of the internals and lets the people making stuff have fun :~~~~

**Comment by RangerMauve** [comment]
Dat workshop at OurNetworks.

TODO: Collect links from people that made websites, get in touch with other dat workshop speaker.

**Comment by RangerMauve** [comment]
https://twitter.com/_ournetworks/status/1175889703020769280

**Comment by RangerMauve** [comment]
@mafintosh made a blog post about the new stuff coming out https://twitter.com/mafintosh/status/1177259694441861120

**Comment by RangerMauve** [comment]
@agentofuser is working on getting Rust crates hosted on Dat. 

SSB: %M8DEDuxZZhg7Ly4VVJnE3Az1N7tSCWw5v2AuO2ay3h8=.sha256

Dat archive: dat://91067272f618b28f22c02a6f95089e9ffbf120016d8f1023ad74575bd03d77ca

**Comment by agentofuser** [comment]
@RangerMauve I've been having trouble keeping the dat archive up to date. I might be doing something wrong, because running `dat sync` takes up 100+% CPU and is really really slow to create metadata. It can't keep up with the downloads even, which aren't that frequent, so I haven't been able to catch up to the latest crates. Would this be because of too many very small files? Is there some tweaking I can do to speed it up? Thanks!

**Comment by RangerMauve** [comment]
@agentofuser Not sure to be honest. The new version of dat changes a bunch of how the storage works, so it might help with your performance issues when it comes out. I'd keep an eye out for an announcement some time soon. 💜

**Comment by okdistribute** [comment]
@agentofuser yes, this is exactly what dat 2.0 helps with -- tons of small files bork dat currently

**Comment by RangerMauve** [comment]
Whoops, kinda late on this, but I'm putting the newsletter together now.
