### ISSUE TITLE
Brainstorming on how to do this

### ISSUE THREAD

**Issue by RangerMauve** [datproject/newsletter#2]
I'd like to get the newsletter figured out some time before the end of the month.

This is following up from the conversation [here](https://github.com/datproject/planning/issues/6)

Here's what I'm thinking we'll need to figure out

- [x] Reach out to the community to learn what they'd like to see
  - [x] Links for new things?
  - [x] Updates from the dat project / what our focus is
  - [x] Summaries of working group / comm comm meetings?
- [x] Figure out how the posts will be authored
  - [x] Markdown?
  - [x] A template?
- [x] Figure out how the posts will be sent out
  - [ ] Github Hooks?
  - [x] Pull requests?
  - [x] Manually hitting send?
- [x] Frequency?
  - [x] Every month?
  - [ ] Every two weeks?

cc @todrobbins @joehand @karissa

**Comment by mafintosh** [comment]
My vote is for monthly

**Comment by todrobbins** [comment]
I agree with @mafintosh. The newsletter will be more sustainable that way.

**Comment by todrobbins** [comment]
@RangerMauve, maybe you've considered this, but seeding the newsletter via dat+hashbase.io would be a good use case. We definitely can utilize Mailchimp for distribution, but having the content live, at least as a mirror within the dat ecosystem would be great.

I'd be happy to write content/edit and do the design/layout work since I'm not as savvy on the technical developments. Let me know what you think though.

**Comment by RangerMauve** [comment]
Yeah! That'd be really cool. :D (for both of those points)

**Comment by RangerMauve** [comment]
Wanna maybe draft something up based on the newsletter Joe released in #1?

If you could also explore plugging markdown into the newsletter that'd be handy.

**Comment by todrobbins** [comment]
Sounds good! Can I get write permissions for this repo?

**Comment by RangerMauve** [comment]
Of course! Gimmi a sec

**Comment by RangerMauve** [comment]
Oops. Apparently I can't do that. Ping @karissa @joehand

**Comment by karissa** [comment]
+1 on monthly. I think markdown works fine and we could transfer the content to mailchimp as well as a dat mirror pretty easily.

**Comment by karissa** [comment]
@todrobbins done

**Comment by todrobbins** [comment]
Rad! Thanks! See #3.

**Comment by hossameldeen** [comment]
Don't know if it's too late to answer:

**What I'd like to see:**
- State of fundamental projects in the dat ecosystem. E.g., dat-js, beaker-identities, ... etc.
- Community projects in the dat ecosystem (and to be able to market such projects on the newsletter). E.g., a website like my https://transparent-salaries.hashbase.io/

**Frequency:** 2 weeks.

**Comment by hossameldeen** [comment]
One more thing I'd like to see: what people have been working on the last 2 weeks/month. E.g.,:

- **X** has implemented features A & B in project C. His/Her hope in the next 2 weeks is to implement add features D & E in project C & fix some issues 1, 2, 3 in project F.
- **Y** got sidetracked and explored G a little bit, and his/her focus for the next 2 weeks is going back to working on H.

My intention of this is _not_ to put pressure on the well-known people; actually I want anyone to be able to add themselves to the list if they want (or remove, of course). My intention of this is to help form a big picture of the community, and to create a sense of "You're not alone".
