### ISSUE TITLE
Why aren't paid projects in the spirit of the newsletter?

### ISSUE THREAD

**Issue by hossameldeen** [datproject/newsletter#6]
**Context:**
- In #5, the April newsletter, I wanted to add [Transparent Salaries](https://github.com/hossameldeen/transparent-salaries) under Community Projects.
- Transparent Salaries is a Beaker-Browser website that you can buy copies of from Gumroad.
- @RangerMauve refused to add it: "I don't think that paid projects are in the spirit of the newsletter.".

I clearly disagree. And, to be honest, Transparent Salaries in a limbo state and adding it doesn't really matter much to me. But I think refusing paid projects might set a dangerous precedent in the community.

So, what are the reasons paid projects aren't in the spirit of this newsletter?

**Comment by karissa** [comment]
@hossameldeen thanks for wanting to contribute to the newsletter. Right now there are a lot of items and we are limiting it. Thanks for understanding!

**Comment by hossameldeen** [comment]
A note for the future: I didn't understand.
