### ISSUE TITLE
June Newsletter Planning

### ISSUE THREAD

**Issue by RangerMauve** [datproject/newsletter#9]
Hey all!

Post any links or ideas for the newsletter for June here. 😁

**Comment by RangerMauve** [comment]
CC @brechtcs for when you're ready with the blog post

**Comment by RangerMauve** [comment]
Kicks Condor's article about their experience using Dat for Duxtape:

https://www.kickscondor.com/on-dat/

dat://duxtape.kickscondor.com/

**Comment by erangell** [comment]
Hi Mauve,
If you missed my article for the previous issue, here it is: https://github.com/erangell/Articles/blob/master/OpportunitiesForDecentralizedTechInEducation.md

**Comment by RangerMauve** [comment]
Mention introduction to Kappa-core by @noffle

https://github.com/kappa-db/kappa-core#introduction

**Comment by noffle** [comment]
@RangerMauve I'm working on some fuller blog posts next week that will hopefully be even better to share!

**Comment by madjin** [comment]
I used Dat for hosting demos to many awesome webvr examples here:

https://madjin.github.io/janus-guide/#/examples/README
https://hashbase.io/webxr

**Comment by cblgh** [comment]
from the top of my head, feel free to pick whichever ones you want! (might update if i finish some in-progress stuff :)
* @dwblair created a cool intro to filesharing with beaker https://mosspig.hashbase.io/posts/beaker/
* i released [cabal-headless](https://github.com/cabal-club/cabal-headless) to make it easier to write small experiments that use cabal
* [cabal-desktop](https://github.com/cabal-club/cabal-desktop/releases/tag/v2.0.3) saw a new release adding topics, removing cabals and slash commands
* a really cool person started work on an [SDK for Dat](https://github.com/datproject/sdk), and dreamed up an [API](https://github.com/datproject/sdk/blob/master/Dream%20API-Promises.md) (!!!!)

**Comment by decentral1se** [comment]
https://github.com/datpy - Python implementation is finally getting off the ground!

**Comment by RangerMauve** [comment]
@decentral1se Oh _hell yeah_! That's awesome!

**Comment by dwblair** [comment]
Neeaaat!  It'll be so cool to play with merkle trees in Python :)

Oh, and I'll mention that we started using @cblgh 's awesome [cabal-headless](https://github.com/cabal-club/cabal-headless) code (mentioned above) to experiment with [p5.js](https://p5js.org/) and [jsnetworkx](http://jsnetworkx.org/) in order to visualize cabal data:  

- https://github.com/dwblair/cabal-p5js
- https://github.com/dwblair/cabal-netx

If it's too late for this newsletter issue, no worries  :)

Cheerio!
D

Cheerio!

**Comment by RangerMauve** [comment]
Still drafting up the newsletter. Would anybody have time tomorrow to review it before I publish? :)

**Comment by dwblair** [comment]
Cool! I can help review for sure!

**Comment by RangerMauve** [comment]
@dwblair Thank you! I'll ping you when it's ready. 💜💜

**Comment by RangerMauve** [comment]
Newsletter got released! :D
